language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpoppler-dev libfontforge-dev libspiro-dev
before_script: 
  - cmake .
script:
  - make
  - sudo make install
  - pdf2htmlex -v
branches:
  only:
    - master
