language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:fontforge/fontforge --yes
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpoppler-dev libpoppler-private-dev libspiro-dev libcairo-dev libpango1.0-dev libfreetype6-dev libltdl-dev libfontforge-dev python-imaging python-selenium ttfautohint firefox xvfb
  - export DISPLAY=:99.0
  - test/start_xvfb.sh
  - sleep 5
before_script: 
  - cmake -DENABLE_SVG=ON .
script:
  - make
  - ctest --output-on-failure
  - sudo make install
  - /usr/local/bin/pdf2htmlEX -v
branches:
  only:
    - master
    - incoming
    - travis
